filepath = "D:/MakingApps/Apps/HelloLogline/src/logline-analyzer.jsx"

with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

# Use unicode escape for the Korean box-drawing chars in the markers
# The actual chars: ─── (U+2500 repeated)
start_marker = '      {/* \u2500\u2500\u2500 Accordion stages \u2500\u2500\u2500 */}\n      <div ref={mainContentRef} style={{\n        maxWidth: 860, width: "100%", margin: "0 auto", boxSizing: "border-box",\n        padding: isMobile ? "16px 12px 80px" : "24px 28px 80px",\n      }}>'

end_marker = '          </StageAccordion>\n\n        </div>'

start_idx = content.find(start_marker)
end_idx = content.find(end_marker) + len(end_marker)

if start_idx == -1:
    print("ERROR: Start marker not found")
    exit(1)

new_section = (
    '      {/* \u2500\u2500\u2500 Sidebar + Stage Layout \u2500\u2500\u2500 */}\n'
    '      <div ref={mainContentRef} style={{ width: "100%", boxSizing: "border-box" }}>\n'
    '\n'
    '          {/* \u2500\u2500 \ub370\ubaa8 \ubaa8\ub4dc \ubc30\ub108 \u2500\u2500 */}\n'
    '          {isDemoMode && (\n'
    '            <div style={{ maxWidth: isMobile ? "100%" : 990, margin: "0 auto", padding: isMobile ? "12px 12px 0" : "16px 28px 0" }}>\n'
    '              <div style={{ marginBottom: 16, padding: "14px 18px", borderRadius: 12, background: "rgba(255,209,102,0.07)", border: "1px solid rgba(255,209,102,0.25)", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}>\n'
    '                <div style={{ display: "flex", alignItems: "center", gap: 10 }}>\n'
    '                  <span style={{ fontSize: 16 }}>\U0001f3ac</span>\n'
    '                  <div>\n'
    '                    <div style={{ fontSize: 12, fontWeight: 700, color: "#FFD166", marginBottom: 2 }}>\ub370\ubaa8 \ubaa8\ub4dc \u2014 \uc0d8\ud50c \ubd84\uc11d \uacb0\uacfc \uccb4\ud5d8 \uc911</div>\n'
    '                    <div style={{ fontSize: 11, color: "var(--c-tx-45)", fontFamily: "\'Noto Sans KR\', sans-serif" }}>\ub85c\uadf8\ub77c\uc778: "{DEMO_LOGLINE.slice(0, 40)}\u2026" \u2014 8\ub2e8\uacc4 \uacb0\uacfc\ub97c \uc790\uc720\ub86d\uac8c \ub458\ub7ec\ubcf4\uc138\uc694.</div>\n'
    '                  </div>\n'
    '                </div>\n'
    '                <div style={{ display: "flex", gap: 8, flexShrink: 0 }}>\n'
    '                  <button\n'
    '                    onClick={() => { deactivateDemo(); setShowApiKeyModal(true); }}\n'
    '                    style={{ padding: "7px 14px", borderRadius: 8, border: "none", background: "#FFD166", color: "#0d0d1a", fontSize: 11, fontWeight: 800, cursor: "pointer", fontFamily: "\'Noto Sans KR\', sans-serif" }}\n'
    '                  >\n'
    '                    \ub0b4 API \ud0a4\ub85c \uc2dc\uc791\n'
    '                  </button>\n'
    '                  <button\n'
    '                    onClick={deactivateDemo}\n'
    '                    style={{ padding: "7px 12px", borderRadius: 8, border: "1px solid rgba(255,209,102,0.3)", background: "transparent", color: "#FFD166", fontSize: 11, cursor: "pointer" }}\n'
    '                  >\n'
    '                    \ub370\ubaa8 \uc885\ub8cc\n'
    '                  </button>\n'
    '                </div>\n'
    '              </div>\n'
    '            </div>\n'
    '          )}\n'
    '\n'
    '          <SidebarLayout\n'
    '            isMobile={isMobile}\n'
    '            stageProps={{\n'
    '              renderStage: (stageId) => {\n'
    '                switch (stageId) {\n'
    '                  case "1": return (\n'
    '                    <Stage1Content\n'
    '                      result={result}\n'
    '                      setResult={setResult}\n'
    '                      loading={loading}\n'
    '                      error={error}\n'
    '                      analyze={analyze}\n'
    '                      compareMode={compareMode}\n'
    '                      setCompareMode={setCompareMode}\n'
    '                      logline2={logline2}\n'
    '                      setLogline2={setLogline2}\n'
    '                      result2={result2}\n'
    '                      loading2={loading2}\n'
    '                      selectedDuration={selectedDuration}\n'
    '                      setSelectedDuration={setSelectedDuration}\n'
    '                      customTheme={customTheme}\n'
    '                      setCustomTheme={setCustomTheme}\n'
    '                      customDurationText={customDurationText}\n'
    '                      setCustomDurationText={setCustomDurationText}\n'
    '                      customFormatLabel={customFormatLabel}\n'
    '                      setCustomFormatLabel={setCustomFormatLabel}\n'
    '                      activeTab={activeTab}\n'
    '                      setActiveTab={setActiveTab}\n'
    '                      insightResult={insightResult}\n'
    '                      insightLoading={insightLoading}\n'
    '                      insightError={insightError}\n'
    '                      generateInsight={generateInsight}\n'
    '                      earlyCoverageResult={earlyCoverageResult}\n'
    '                      setEarlyCoverageResult={setEarlyCoverageResult}\n'
    '                      earlyCoverageLoading={earlyCoverageLoading}\n'
    '                      earlyCoverageError={earlyCoverageError}\n'
    '                      analyzeEarlyCoverage={analyzeEarlyCoverage}\n'
    '                      setStoryFixes={setStoryFixes}\n'
    '                      setStoryPivots={setStoryPivots}\n'
    '                      setAiImprovement={setAiImprovement}\n'
    '                      academicResult={academicResult}\n'
    '                      apiKey={apiKey}\n'
    '                      serverHasKey={serverHasKey}\n'
    '                    />\n'
    '                  );\n'
    '                  case "2": return (\n'
    '                    <Stage2Content\n'
    '                      expertPanelResult={expertPanelResult}\n'
    '                      setExpertPanelResult={setExpertPanelResult}\n'
    '                      expertPanelLoading={expertPanelLoading}\n'
    '                      expertPanelError={expertPanelError}\n'
    '                      runExpertPanel={runExpertPanel}\n'
    '                    />\n'
    '                  );\n'
    '                  case "3": return (\n'
    '                    <Stage3Content\n'
    '                      result={result}\n'
    '                      charGuide={charGuide}\n'
    '                      setCharGuide={setCharGuide}\n'
    '                      charGuideLoading={charGuideLoading}\n'
    '                      charGuideError={charGuideError}\n'
    '                      generateCharGuide={generateCharGuide}\n'
    '                      showManualCharInput={showManualCharInput}\n'
    '                      setShowManualCharInput={setShowManualCharInput}\n'
    '                      treatmentChars={treatmentChars}\n'
    '                      setTreatmentChars={setTreatmentChars}\n'
    '                      shadowResult={shadowResult}\n'
    '                      setShadowResult={setShadowResult}\n'
    '                      shadowLoading={shadowLoading}\n'
    '                      shadowError={shadowError}\n'
    '                      analyzeShadow={analyzeShadow}\n'
    '                      authenticityResult={authenticityResult}\n'
    '                      setAuthenticityResult={setAuthenticityResult}\n'
    '                      authenticityLoading={authenticityLoading}\n'
    '                      authenticityError={authenticityError}\n'
    '                      analyzeAuthenticity={analyzeAuthenticity}\n'
    '                      charDevResult={charDevResult}\n'
    '                      setCharDevResult={setCharDevResult}\n'
    '                      charDevLoading={charDevLoading}\n'
    '                      charDevError={charDevError}\n'
    '                      charDevFeedback={charDevFeedback}\n'
    '                      setCharDevFeedback={setCharDevFeedback}\n'
    '                      charDevRefineLoading={charDevRefineLoading}\n'
    '                      charDevHistory={charDevHistory}\n'
    '                      setCharDevHistory={setCharDevHistory}\n'
    '                      analyzeCharacterDev={analyzeCharacterDev}\n'
    '                      charAllDone={charAllDone}\n'
    '                      editingCharacter={editingCharacter}\n'
    '                      setEditingCharacter={setEditingCharacter}\n'
    '                      charEditDraft={charEditDraft}\n'
    '                      setCharEditDraft={setCharEditDraft}\n'
    '                      writerEdits={writerEdits}\n'
    '                      clearWriterEdit={clearWriterEdit}\n'
    '                      setWriterEdit={setWriterEdit}\n'
    '                      refineCharDev={refineCharDev}\n'
    '                      undoHistory={undoHistory}\n'
    '                    />\n'
    '                  );\n'
    '                  case "4": return (\n'
    '                    <Stage4Content\n'
    '                      result={result}\n'
    '                      structureResult={structureResult}\n'
    '                      setStructureResult={setStructureResult}\n'
    '                      structureLoading={structureLoading}\n'
    '                      structureError={structureError}\n'
    '                      valueChargeResult={valueChargeResult}\n'
    '                      setValueChargeResult={setValueChargeResult}\n'
    '                      valueChargeLoading={valueChargeLoading}\n'
    '                      valueChargeError={valueChargeError}\n'
    '                      analyzeStructureAll={analyzeStructureAll}\n'
    '                      structureAllLoading={structureAllLoading}\n'
    '                      structureAllDone={structureAllDone}\n'
    '                      comparableResult={comparableResult}\n'
    '                      setComparableResult={setComparableResult}\n'
    '                      comparableLoading={comparableLoading}\n'
    '                      comparableError={comparableError}\n'
    '                      analyzeComparableWorks={analyzeComparableWorks}\n'
    '                      academicResult={academicResult}\n'
    '                      mythMapResult={mythMapResult}\n'
    '                      koreanMythResult={koreanMythResult}\n'
    '                      expertPanelResult={expertPanelResult}\n'
    '                      barthesCodeResult={barthesCodeResult}\n'
    '                      shadowResult={shadowResult}\n'
    '                      authenticityResult={authenticityResult}\n'
    '                      charDevResult={charDevResult}\n'
    '                      subtextResult={subtextResult}\n'
    '                      themeResult={themeResult}\n'
    '                      synopsisMode={synopsisMode}\n'
    '                      setSynopsisMode={setSynopsisMode}\n'
    '                      NARRATIVE_FRAMEWORKS={NARRATIVE_FRAMEWORKS}\n'
    '                      selectedFramework={selectedFramework}\n'
    '                      setSelectedFramework={setSelectedFramework}\n'
    '                      frameworkInfoId={frameworkInfoId}\n'
    '                      setFrameworkInfoId={setFrameworkInfoId}\n'
    '                      directionCount={directionCount}\n'
    '                      setDirectionCount={setDirectionCount}\n'
    '                      generateSynopsis={generateSynopsis}\n'
    '                      synopsisLoading={synopsisLoading}\n'
    '                      synopsisError={synopsisError}\n'
    '                      synopsisResults={synopsisResults}\n'
    '                      selectedSynopsisIndex={selectedSynopsisIndex}\n'
    '                      setSelectedSynopsisIndex={setSelectedSynopsisIndex}\n'
    '                      selectedDuration={selectedDuration}\n'
    '                      treatmentChars={treatmentChars}\n'
    '                      pipelineResult={pipelineResult}\n'
    '                      setPipelineResult={setPipelineResult}\n'
    '                      pipelineHistory={pipelineHistory}\n'
    '                      setPipelineHistory={setPipelineHistory}\n'
    '                      editingSynopsis={editingSynopsis}\n'
    '                      setEditingSynopsis={setEditingSynopsis}\n'
    '                      synopsisEditDraft={synopsisEditDraft}\n'
    '                      setSynopsisEditDraft={setSynopsisEditDraft}\n'
    '                      writerEdits={writerEdits}\n'
    '                      setWriterEdit={setWriterEdit}\n'
    '                      clearWriterEdit={clearWriterEdit}\n'
    '                      treatmentResult={treatmentResult}\n'
    '                      setTreatmentStale={setTreatmentStale}\n'
    '                      beatSheetResult={beatSheetResult}\n'
    '                      setBeatSheetStale={setBeatSheetStale}\n'
    '                      scenarioDraftResult={scenarioDraftResult}\n'
    '                      setScenarioDraftStale={setScenarioDraftStale}\n'
    '                      pipelineFeedback={pipelineFeedback}\n'
    '                      setPipelineFeedback={setPipelineFeedback}\n'
    '                      refinePipelineSynopsis={refinePipelineSynopsis}\n'
    '                      pipelineRefineLoading={pipelineRefineLoading}\n'
    '                      undoHistory={undoHistory}\n'
    '                    />\n'
    '                  );\n'
    '                  case "5": return (\n'
    '                    <Stage5Content\n'
    '                      showTreatmentPanel={showTreatmentPanel}\n'
    '                      setShowTreatmentPanel={setShowTreatmentPanel}\n'
    '                      treatmentChars={treatmentChars}\n'
    '                      setTreatmentChars={setTreatmentChars}\n'
    '                      treatmentStructure={treatmentStructure}\n'
    '                      setTreatmentStructure={setTreatmentStructure}\n'
    '                      selectedDuration={selectedDuration}\n'
    '                      charDevResult={charDevResult}\n'
    '                      treatmentResult={treatmentResult}\n'
    '                      setTreatmentResult={setTreatmentResult}\n'
    '                      treatmentLoading={treatmentLoading}\n'
    '                      treatmentError={treatmentError}\n'
    '                      treatmentStale={treatmentStale}\n'
    '                      setTreatmentStale={setTreatmentStale}\n'
    '                      treatmentHistory={treatmentHistory}\n'
    '                      setTreatmentHistory={setTreatmentHistory}\n'
    '                      generateTreatment={generateTreatment}\n'
    '                      treatmentFeedback={treatmentFeedback}\n'
    '                      setTreatmentFeedback={setTreatmentFeedback}\n'
    '                      refineTreatment={refineTreatment}\n'
    '                      treatmentRefineLoading={treatmentRefineLoading}\n'
    '                      treatmentBefore={treatmentBefore}\n'
    '                      showTreatmentBefore={showTreatmentBefore}\n'
    '                      setShowTreatmentBefore={setShowTreatmentBefore}\n'
    '                      editingTreatment={editingTreatment}\n'
    '                      setEditingTreatment={setEditingTreatment}\n'
    '                      treatmentEditDraft={treatmentEditDraft}\n'
    '                      setTreatmentEditDraft={setTreatmentEditDraft}\n'
    '                      writerEdits={writerEdits}\n'
    '                      setWriterEdit={setWriterEdit}\n'
    '                      setWriterEdits={setWriterEdits}\n'
    '                      clearWriterEdit={clearWriterEdit}\n'
    '                      treatmentCtx={treatmentCtx}\n'
    '                      beatSheetResult={beatSheetResult}\n'
    '                      setBeatSheetResult={setBeatSheetResult}\n'
    '                      beatSheetLoading={beatSheetLoading}\n'
    '                      beatSheetError={beatSheetError}\n'
    '                      beatSheetStale={beatSheetStale}\n'
    '                      setBeatSheetStale={setBeatSheetStale}\n'
    '                      beatSheetHistory={beatSheetHistory}\n'
    '                      setBeatSheetHistory={setBeatSheetHistory}\n'
    '                      generateBeatSheet={generateBeatSheet}\n'
    '                      beatSheetCtx={beatSheetCtx}\n'
    '                      beatScenes={beatScenes}\n'
    '                      expandedBeats={expandedBeats}\n'
    '                      setExpandedBeats={setExpandedBeats}\n'
    '                      editingBeats={editingBeats}\n'
    '                      setEditingBeats={setEditingBeats}\n'
    '                      beatEditDrafts={beatEditDrafts}\n'
    '                      setBeatEditDrafts={setBeatEditDrafts}\n'
    '                      structureTwistLoading={structureTwistLoading}\n'
    '                      structureTwistError={structureTwistError}\n'
    '                      structureTwistResult={structureTwistResult}\n'
    '                      analyzeStructureTwist={analyzeStructureTwist}\n'
    '                      GENRE_BEAT_HINTS={GENRE_BEAT_HINTS}\n'
    '                      undoHistory={undoHistory}\n'
    '                      beatSheetFeedback={beatSheetFeedback}\n'
    '                      setBeatSheetFeedback={setBeatSheetFeedback}\n'
    '                      refineBeatSheet={refineBeatSheet}\n'
    '                      beatSheetRefineLoading={beatSheetRefineLoading}\n'
    '                      beatSheetBefore={beatSheetBefore}\n'
    '                      showBeatSheetBefore={showBeatSheetBefore}\n'
    '                      setShowBeatSheetBefore={setShowBeatSheetBefore}\n'
    '                      dialogueDevResult={dialogueDevResult}\n'
    '                      setDialogueDevResult={setDialogueDevResult}\n'
    '                      dialogueDevLoading={dialogueDevLoading}\n'
    '                      dialogueDevError={dialogueDevError}\n'
    '                      analyzeDialogueDev={analyzeDialogueDev}\n'
    '                    />\n'
    '                  );\n'
    '                  case "6": return (\n'
    '                    <Stage6Content\n'
    '                      scenarioDraftResult={scenarioDraftResult}\n'
    '                      setScenarioDraftResult={setScenarioDraftResult}\n'
    '                      scenarioDraftLoading={scenarioDraftLoading}\n'
    '                      scenarioDraftError={scenarioDraftError}\n'
    '                      generateScenarioDraft={generateScenarioDraft}\n'
    '                      scenarioDraftStale={scenarioDraftStale}\n'
    '                      setScenarioDraftStale={setScenarioDraftStale}\n'
    '                      scenarioDraftHistory={scenarioDraftHistory}\n'
    '                      setScenarioDraftHistory={setScenarioDraftHistory}\n'
    '                      refineScenarioDraft={refineScenarioDraft}\n'
    '                      scenarioDraftRefineLoading={scenarioDraftRefineLoading}\n'
    '                      scenarioDraftFeedback={scenarioDraftFeedback}\n'
    '                      setScenarioDraftFeedback={setScenarioDraftFeedback}\n'
    '                      scenarioDraftCtx={scenarioDraftCtx}\n'
    '                      scenarioDraftBefore={scenarioDraftBefore}\n'
    '                      showScenarioDraftBefore={showScenarioDraftBefore}\n'
    '                      setShowScenarioDraftBefore={setShowScenarioDraftBefore}\n'
    '                      undoHistory={undoHistory}\n'
    '                    />\n'
    '                  );\n'
    '                  case "7": return (\n'
    '                    <Stage7Content\n'
    '                      scriptCoverageResult={scriptCoverageResult}\n'
    '                      setScriptCoverageResult={setScriptCoverageResult}\n'
    '                      valuationResult={valuationResult}\n'
    '                      setValuationResult={setValuationResult}\n'
    '                      scriptCoverageLoading={scriptCoverageLoading}\n'
    '                      valuationLoading={valuationLoading}\n'
    '                      scriptCoverageError={scriptCoverageError}\n'
    '                      valuationError={valuationError}\n'
    '                      analyzeScriptCoverage={analyzeScriptCoverage}\n'
    '                      analyzeValuation={analyzeValuation}\n'
    '                    />\n'
    '                  );\n'
    '                  case "8": return (\n'
    '                    <Stage8Content\n'
    '                      scriptCoverageResult={scriptCoverageResult}\n'
    '                      rewriteGuide={rewriteGuide}\n'
    '                      setRewriteGuide={setRewriteGuide}\n'
    '                      rewriteGuideLoading={rewriteGuideLoading}\n'
    '                      rewriteGuideError={rewriteGuideError}\n'
    '                      generateRewriteGuide={generateRewriteGuide}\n'
    '                      rewriteDiagResult={rewriteDiagResult}\n'
    '                      setRewriteDiagResult={setRewriteDiagResult}\n'
    '                      rewriteDiagLoading={rewriteDiagLoading}\n'
    '                      rewriteDiagError={rewriteDiagError}\n'
    '                      generateRewriteDiag={generateRewriteDiag}\n'
    '                      scenarioDraftResult={scenarioDraftResult}\n'
    '                      partialRewriteInstruction={partialRewriteInstruction}\n'
    '                      setPartialRewriteInstruction={setPartialRewriteInstruction}\n'
    '                      generatePartialRewrite={generatePartialRewrite}\n'
    '                      partialRewriteLoading={partialRewriteLoading}\n'
    '                      partialRewriteError={partialRewriteError}\n'
    '                      partialRewriteResult={partialRewriteResult}\n'
    '                      setPartialRewriteResult={setPartialRewriteResult}\n'
    '                      fullRewriteNotes={fullRewriteNotes}\n'
    '                      setFullRewriteNotes={setFullRewriteNotes}\n'
    '                      generateFullRewrite={generateFullRewrite}\n'
    '                      fullRewriteLoading={fullRewriteLoading}\n'
    '                      fullRewriteError={fullRewriteError}\n'
    '                      fullRewriteResult={fullRewriteResult}\n'
    '                      setFullRewriteResult={setFullRewriteResult}\n'
    '                    />\n'
    '                  );\n'
    '                  default: return null;\n'
    '                }\n'
    '              }\n'
    '            }}\n'
    '          />\n'
    '\n'
    '        </div>'
)

new_content = content[:start_idx] + new_section + content[end_idx:]

with open(filepath, "w", encoding="utf-8") as f:
    f.write(new_content)

print("Done!")
print("New file lines:", new_content.count('\n'))
